#These are the connection adapters for the app
development:
  adapter: postgresql
  encoding: unicode
  database: app0521_development
  pool: 5
  username: mam
  password: techno8021

  
test:
  adapter: postgresql
  encoding: unicode
  database: app0521_test
  pool: 5
  username: app0521
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: app0521_production
  pool: 5
  username: mam
  password: techno8021

#This is for the sqlite3 DB which contains the yellow pages data
#yplistings_development:
 #adapter: sqlite3
 #database: db/yplistings.sqlite3
 #pool: 5
 #timeout: 5000

overseasworkers_development:
 adapter: sqlite3
 database: db/overseasworkers.sqlite3
 pool: 5
 timeout: 5000
