#These are the connection adapters for the app
development:
  adapter: postgresql
  encoding: unicode
  database: app0521_development
  pool: 5
  username: mam
  password: techno8021

  
test:
  adapter: postgresql
  encoding: unicode
  database: app0521_test
  pool: 5
  username: app0521
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: app0521_production
  pool: 5
  username: mam
  password: techno8021
