#These are the connection adapters for the app
development:
  adapter: postgresql
  encoding: unicode
  database: app0521_development
  pool: 5
  username: mam
  password: techno8021

  
test:
  adapter: postgresql
  encoding: unicode
  database: app0521_test
  pool: 5
  username: app0521
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: app0521_production
  pool: 5
  username: mam
  password: techno8021
#These are the database adapters for the connection that needs to be established 
#with the app: bmc_mam in order to copy the listings from there
bmc_mam_development:
  adapter: postgresql
  encoding: unicode
  database: bmc_mam_development
  pool: 5
  username: mam
  password: techno8021